### PR TITLE
chore(back-office): remove appeals back office resources

### PR DESCRIPTION
**Pull request by beejjacobs**
# Pull Request Template

## Describe your changes

New resources are all now managed in the Appeals Back Office repo
https://github.com/Planning-Inspectorate/appeals-back-office

https://pins-ds.atlassian.net/browse/DEV-239

## Type of change 🧩

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [ ] Other (please explain in the description section above)

## Checklist before requesting a review

- [ ] My code follows the style guidelines of this project
- [ ] My code changes do not include any hardcoded secrets or passwords
- [ ] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [ ] My Tech Lead is aware of any infrastructure changes that will cost money

### CODE REVIEW

**Comment by beejjacobs** [comment]
Extracted from the Dev Plan, here are the resources to be deleted:

```yaml
azurerm_application_insights:
  back_office_appeals_insights
azurerm_key_vault_secret:
  app_secret["back-office-appeals-gov-notify-api-key"]
  app_secret["back-office-appeals-test-mailbox"]
  back_office_appeals_redis_cache_connection_string_secret
  back_office_appeals_sql_connection_string
  back_office_appeals_sql_connection_string_app
  back_office_sql_server_password_appeals_app
  back_office_sql_server_username_appeals_app
  bo_appeals_insights_connection_string
azurerm_monitor_metric_alert:
  back_office_appeals_sql_db_cpu_alert
  back_office_appeals_sql_db_deadlock_alert
  back_office_appeals_sql_db_dtu_alert
  back_office_appeals_sql_db_log_io_alert
  sb_dead_letter_alerts["Appeals BO Events (internal)"]
  sb_dead_letter_alerts["Appeals BO Events (to FO, ODW)"]
  sb_dead_letter_alerts["Appeals FO Submissions"]
azurerm_mssql_database:
  back_office_appeals
azurerm_private_endpoint:
  back_office_appeals_redis_cache
azurerm_redis_cache:
  back_office_appeals_redis_cache
azurerm_servicebus_topic:
  appeal_bo_case
  appeal_bo_document
  appeal_bo_document_to_move
  appeal_fo_appellant_submission
  appeal_fo_lpa_response_submission
  listed_building
azurerm_storage_container:
  back_office_appeals_document_container
random_id:
  username_suffix_appeals_app
random_password:
  back_office_sql_server_password_appeals_app
module:
  app_services:
    azurerm_role_assignment:
      appeals_case_officer_documents_access
      appeals_inspector_documents_access
      back_office_appeals_send_service_bus_access
    module:
      app_service["back_office_appeals_api"]:
        azurerm_key_vault_access_policy:
          read_secrets[0]
          read_secrets_staging_slot[0]
        azurerm_linux_web_app:
          web_app
        azurerm_linux_web_app_slot:
          staging
        azurerm_monitor_activity_log_alert:
          app_service_delete
          app_service_stop
        azurerm_monitor_diagnostic_setting:
          web_app_logs
        azurerm_monitor_metric_alert:
          app_service_http_5xx
          app_service_response_time
      app_service["back_office_appeals_frontend"]:
        azurerm_key_vault_access_policy:
          read_secrets[0]
          read_secrets_staging_slot[0]
        azurerm_linux_web_app:
          web_app
        azurerm_linux_web_app_slot:
          staging
        azurerm_monitor_activity_log_alert:
          app_service_delete
          app_service_stop
        azurerm_monitor_diagnostic_setting:
          web_app_logs
        azurerm_monitor_metric_alert:
          app_service_http_5xx
          app_service_response_time
      bo_appeals_casedata_import_function:
        azurerm_role_assignment:
          service_bus_data_receiver_appellant_case
          service_bus_data_receiver_lpa_questionnaire
        azurerm_servicebus_subscription:
          fo_appellant_submission_subscription
          fo_lpaq_submission_subscription
        module:
          bo_appeals_casedata_import_function:
            azurerm_application_insights:
              function_app_insights
            azurerm_linux_function_app:
              function_app
            azurerm_monitor_activity_log_alert:
              function_app_delete
              function_app_stop
            azurerm_monitor_diagnostic_setting:
              function_app_logs
            azurerm_monitor_metric_alert:
              function_app_http_5xx
              function_app_response_time
      bo_appeals_doc_processing_function:
        azurerm_eventgrid_event_subscription:
          malware_scanning_bo_subscription
        azurerm_role_assignment:
          function_blob_data_reader
          function_blob_data_writer
          service_bus_data_receiver_documents_to_move
        azurerm_servicebus_subscription:
          register_bo_document_to_move_subscription
        module:
          bo_appeals_doc_processing_function:
            azurerm_application_insights:
              function_app_insights
            azurerm_linux_function_app:
              function_app
            azurerm_monitor_activity_log_alert:
              function_app_delete
              function_app_stop
            azurerm_monitor_diagnostic_setting:
              function_app_logs
            azurerm_monitor_metric_alert:
              function_app_http_5xx
              function_app_response_time
      bo_appeals_scheduler_function:
        azurerm_role_assignment:
          function_blob_data_writer
        module:
          bo_appeals_scheduler_function:
            azurerm_application_insights:
              function_app_insights
            azurerm_linux_function_app:
              function_app
            azurerm_monitor_activity_log_alert:
              function_app_delete
              function_app_stop
            azurerm_monitor_diagnostic_setting:
              function_app_logs
            azurerm_monitor_metric_alert:
              function_app_http_5xx
              function_app_response_time
      bo_appeals_user_import_function:
        azurerm_role_assignment:
          service_bus_data_receiver_service_user
        azurerm_servicebus_subscription:
          register_odw_serviceuser_subscription
        module:
          bo_appeals_user_import_function:
            azurerm_application_insights:
              function_app_insights
            azurerm_linux_function_app:
              function_app
            azurerm_monitor_activity_log_alert:
              function_app_delete
              function_app_stop
            azurerm_monitor_diagnostic_setting:
              function_app_logs
            azurerm_monitor_metric_alert:
              function_app_http_5xx
              function_app_response_time
```

**Review by bryn-pins — APPROVED** [review]
looks ok from an appeals FO perspective

**Review by fabfab-kc — APPROVED** [review]
LGTM! I had some doubts around the variable `service_user_topic_id`, which should still be used by applications, but its value is empty...

**Comment by beejjacobs** [comment]
> service_user_topic_id

TF Lint told me it wasn't used! I think they just have a different name for it (e.g. `back_office_service_bus_nsip_service_user_topic_id`)

**Comment by beejjacobs** [comment]
Thanks for looking everyone. Here goes.

**Pull request merged**
